---

- hosts: dell6420
  tasks:
    - name: Kopiuję skrypt bitlocker.ps1 na dysk 
      win_copy:
        src: bitlocker.ps1
        dest: C:\Users\winuser\Desktop\bitlocker.ps1

    - name: Sprawdzam czy moduł TPM jest włączony
      win_shell: |
        if ($WindowsVer -and !$TPMNotEnabled) 
        { Initialize-Tpm -AllowClear -AllowPhysicalPresence -ErrorAction SilentlyContinue }

    - name: szyfruję dysk ze skryptu
      win_shell: C:\Users\winuser\Desktop\bitlocker.ps1

    - name: Odczytuję klucz odzyskiwania ---- szyfrowanie nadal trwa
      win_shell: (Get-BitLockerVolume -MountPoint C).KeyProtector
      # win_shell: 'manage-bde -protectors -get C:'
      register: RecoveryKey

    - name: Przenoszę klucz do pliku /home/bitlocker/{{ansible_hostname}}   
      local_action: 
        module: copy 
        content: "{{ RecoveryKey.stdout_lines }}"
        dest: /home/szymon/{{ ansible_hostname }}

    - name: Usuwam skrypy bitlocker.ps1 z systemu
      win_file:
        path: C:\Users\winuser\Desktop\bitlocker.ps1
        state: absent
        
    - name: Odczytuję status szyfrowania
      win_shell: 'manage-bde -status'
      register: output
    - debug: var=output.stdout_lines
...