---
- hosts: dell6420
  roles:
   #   - ping
      - { role: create_user, user_name: uzytkownik1, user_fullname: "Użytkownik1" }
      - bitlocker
      - { role: choco_install, software: notepadplusplus}
      - { role: choco_install, software: openvpn }
      - { role: choco_install, software: adobereader }
      - { role: choco_install, software: windirstat }
      - { role: choco_install, software: firefox }
      - add_wifi
      - win_update
- import_playbook: tightvnc.yml
- import_playbook: RegEdit.yml
- import_playbook: bitlocker_check.yml


...