---
#To jest komentarz
- name: Przykładowy Yaml
  hosts: adres.serwera.pl
  tasks:
    - name: "Ping w10 Pro"
      win_ping:
...
#  roles:
 #     - ping
  #    - { role: create_user, user_name: test, user_fullname: "Test", user_pass_expiry: False }
#      - { role: choco_install, software: notepadplusplus}
#      - { role: choco_install, software: firefox }