---
- hosts: dell6420
  tasks:

  - name: '"Ten komputer" domyślnie po otworzeniu eksploratora plików'
    win_regedit:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: LaunchTo
      data: 1 #1 dla Ten Komputer, a 2 dla Szybki Dostęp
      type: dword
      state: present
    ignore_errors: yes

  - name: Wyłączenie Cortany z paska zadań
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsSearch
      name: AllowCortana
      data: 0 #0 dla wyłączenia, 1 dla włączenia Cortany
      type: dword
      state: present
    ignore_errors: yes

  # - name: Wyłącz automatyczne aktualizacje Windows
  #   win_regedit:
  #     path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
  #     name: NoAutoUpdate
  #     data: 0
  #     type: dword
  #     state: present

  - name: Włącz pokazywanie ukrytych plików i folderów
    win_regedit:
      path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: Hidden
      data: 1
      type: dword
      state: present
    ignore_errors: yes
...