---
- hosts: host2
  tasks:

  - name: '"Ten komputer" domyślnie po otworzeniu eksploratora plików'
    win_regedit:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: LaunchTo
      data: 1 #1 dla Ten Komputer, a 2 dla Szybki Dostęp
      type: dword

  - name: Disable Cortana (Windows 10 Anniversary+)
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsSearch
      name: AllowCortana
      data: 0 #0 dla wyłączenia, 1 dla włączenia Cortany
      type: dword


...