---
- hosts: host1
  gather_facts: no
  roles:
      - ping
      - { role: remove_user, user_name: uzytkownik1 }
      #- { role: choco_remove, software: all}
      - { role: choco_remove, software: openvpn }
      - { role: choco_remove, software: adobereader }
      - { role: choco_remove, software: windirstat }
      - { role: choco_remove, software: firefox }
      - { role: choco_remove, software: tightvnc }

  tasks:
    - name: Usuwam profil WiFi InternetBezprzewodowy
      win_command: 'netsh wlan delete profile name="WirelessProfileName"'
      ignore_errors: yes
    - name: '"Ten komputer" domyślnie po otworzeniu eksploratora plików'
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: LaunchTo
        data: 2 #1 dla Ten Komputer, a 2 dla Szybki Dostęp
        type: dword
        state: present


    - name: Wyłączenie Cortany z paska zadań
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsSearch
        name: AllowCortana
        data: 1 #0 dla wyłączenia, 1 dla włączenia Cortany
        type: dword
        state: present


    - name: Włącz pokazywanie ukrytych plików i folderów
      win_regedit: 
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: Hidden
        data: 1 #1 aby pliki były pokazywane
        type: dword
        state: absent
...