---
- hosts: wirtualne azure
  tasks:
  - name: Usuwanie oprogramowania przez chocolatey
    win_chocolatey:
      name: all #'{{ item }}'
      state: absent
    # with_items:
    # - adobereader
    # - notepadplusplus
    # - windirstat
    # - openvpn
    # - firefox

    ignore_errors: yes
    register: log

  - name: Lista odinstalowanych aplikacji
    debug: var=log.stdout_lines
