- hosts: host2
  vars_files:
    - group_vars/pass.yml
  tasks:
  - name: Instalacja i konfiguracja TightVNC
    
    win_chocolatey: 
      name: tightvnc
      state: latest
    #  install_args: 'SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=tightvnc SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=tightvnc' #  SET_RUNCONTROLINTERFACE VALUE_OF_RUNCONTROLINTERFACE=1' # SET_ACCEPTRFBCONNECTIONS VALUE_OF_ACCEPTRFBCONNECTIONS=1'
    #  install_args: 'SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 "VALUE_OF_PASSWORD={{tightvnc_password}}" SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 "VALUE_OF_CONTROLPASSWORD={{tightvnc_password}}"' # SET_ACCEPTRFBCONNECTIONS VALUE_OF_ACCEPTRFBCONNECTIONS=1'
      install_args: 'SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD="{{ tightvnc_password }}" SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD="{{ tightvnc_password }}"' # SET_RUNCONTROLINTERFACE VALUE_OF_RUNCONTROLINTERFACE=1 SET_ACCEPTRFBCONNECTIONS VALUE_OF_ACCEPTRFBCONNECTIONS=1'
      allow_empty_checksums: yes
    ignore_errors: yes