---
#parametry pobrane z https://www.tightvnc.com/doc/win/TightVNC_2.7_for_Windows_Installing_from_MSI_Packages.pdf
- hosts: dell6420
  tasks:
  - name: Instalacja i konfiguracja TightVNC
    win_chocolatey: 
      name: tightvnc
      state: present
      install_args: 'SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD="{{ tightvnc_password }}" SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD="{{ tightvnc_password }}" SET_RUNCONTROLINTERFACE=1 VALUE_OF_RUNCONTROLINTERFACE=1 SET_ACCEPTRFBCONNECTIONS=1 VALUE_OF_ACCEPTRFBCONNECTIONS=1'
      allow_empty_checksums: yes
    ignore_errors: yes
...