---
- hosts: dell6420
#  gather_facts: yes
#(jeśli chcemy aby aktualizacje działy się na każdym hoście po kolei opcja serial musi być aktywna z parametrem 1)
#  serial: 1
  tasks:
  - name: Instalacja kluczowych aktualizacji windows
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
      state: installed
    register: update_result
  - name: Sprawdzam czy potrzebny jest restart systemu po aktualizacjach
    win_reboot:
      pre_reboot_delay: 2700
      msg: "System zostanie ponownie uruchomiony za okolo 45 minut z powodu instalacji aktualizacji. Proszę zapisać pracę do tego czasu."
    when: update_result.reboot_required

  - name: Powiadomienie dla zalogowanych użytkowników o restarcie
    win_msg:
      display_seconds: 2000
      msg: "System zostanie ponownie uruchomiony za 45 minut z powodu instalacji aktualizacji. Proszę zapisać pracę do tego czasu."
    when: update_result.reboot_required