- hosts: lenovo
  tasks:
  - name: Sprawdzam czy są aktualizacje systemu Windows
    win_updates:
      category_names:
          - CriticalUpdates
          - SecurityUpdates
      state: searched
    register: updatelog
      
    ignore_errors: yes

  - name: Lista aktualizacji
    debug: var=updatelog.found_update_count