---
- name: Sprawdzam czy moduł TPM jest włączony
  win_shell: Get-Tpm | Select-Object -ExpandProperty Tpmready
  register: tpmstatus
  
- name: Przekazuję stan TPM do reszty bloku
  set_fact: tmp={{tpmstatus.stdout}}
  
- block:
  - name: Rozpoczynam szyfrowanie dysku BitLockerem
    win_shell: 'Enable-BitLocker -MountPoint "C:" -EncryptionMethod XtsAes256 -RecoveryPasswordProtector -UsedSpaceOnly -SkipHardwareTest'

  - name: Odczytuję klucz odzyskiwania ---- szyfrowanie nadal trwa
    win_shell: (Get-BitLockerVolume -MountPoint C).KeyProtector
    register: RecoveryKey

  - name: Zapisuję klucz odzyskiwania do pliku /home/bitlocker/{{ansible_hostname}}   
    local_action: 
      module: copy 
      content: "{{ RecoveryKey.stdout_lines }}"
      dest: /home/szymon/{{ ansible_hostname }}
  when: tmp == "True\r\n"

  always:      
    - name: Odczytuję status szyfrowania
      win_shell: 'manage-bde -status'
      register: output
    - debug: var=output.stdout_lines


...