---
- name: Włączenie możliwości instalowania aplikacji innych firm
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    name: AllowAllTrustedApps
    data: 1
    type: dword
    state: present

- name: "Pobieranie i instalacja 7zip"
  win_get_url:
    url: https://www.7-zip.org/a/7z1900.msi
    dest: c:\Users\winuser\Desktop\7zip.msi

- name: "Uruchomienie instalatora"
  win_package:
    path: c:\Users\winuser\Desktop\7zip.msi
    state: present # dla deinstalacji parametr: absent

  

# - name: Pobieranie i instalacja programu spoza repozytorium 
#   win_package:
#     path: "{{ url_adress }}"
#     product_id: "{{ product_id }}"
#     state: present



