- name: Turn on password complexity
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity 
    value: 0  #0 for disabled, 1 for enabled

- name: Set the minimum password length
  community.windows.win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: 5


    # Possible keys:
    # [System Access]
    # MinimumPasswordAge = 0
    # MaximumPasswordAge = 42
    # MinimumPasswordLength = 5
    # PasswordComplexity = 0
    # PasswordHistorySize = 0
    # LockoutBadCount = 0
    # RequireLogonToChangePassword = 0