---
- name: "Dodanie użytkownika {{ user_name }}"
  win_user:
    name: "{{ user_name }}"
    fullname: "{{ user_fullname }}"
    password:
    password_never_expires: no
    update_password: on_create
    user_cannot_change_password: no
    state: present
    groups:
      - "Użytkownicy"
      - "Operatorzy konfiguracji sieci"
  ignore_errors: yes

- name: Kopiuję skrypt ConfigureRemotingForAnsible.ps1 na dysk 
  win_copy:
    src: ConfigureRemotingForAnsible.ps1
    dest: C:\ConfigureRemotingForAnsible.ps1

- name: Włączenie historii zadań menadżera zadadań
  win_shell: wevtutil set-log Microsoft-Windows-TaskScheduler/Operational /enabled:true
  ignore_errors: yes

- name: Dodanie codziennej konfiguracji WinRM do automatycznych zadań windows
  win_scheduled_task:
    name: ConfigureRemotingForAnsible
    start_when_available: yes
    multiple_instances: 2
    enabled: yes
    actions:
    - path: powershell.exe
      working_directory: C:\
      arguments: -ExecutionPolicy Bypass -File "C:\ConfigureRemotingForAnsible.ps1" -CertValidityDays 3650 -EnableCredSSP -ForceNewSSLCert
    triggers:
    - type: boot
    - type: daily
      start_boundary: '2021-01-01T12:00:00'
    username: NT AUTHORITY\SYSTEM
...