--- 
- name: Instalacja aktualizacji systemowych
  block:  
  - name: Instalacja kluczowych aktualizacji windows
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
    register: update_result
  ##- name: co zostało zainstalowane
  #  debug:
  #    msg: "{{ update_result.msg }}"

  - name: Sprawdzam czy potrzebny jest restart systemu po aktualizacjach
    win_reboot:
      shutdown_timeout_sec: 2700
      msg: "System zostanie ponownie uruchomiony za 45 minut z powodu instalacji aktualizacji. Proszę zapisać pracę do tego czasu."
    when: update_result.reboot_required

  always:
    - name: Wynik aktualizacji systemu
      debug:
        var: update_result.msg
...
